In [1]:
import numpy as np

arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [2]:
print("after additin of 2")
print(arr+2)

after additin of 2
[12 22 32 42 52]


In [3]:
print("after multiplication by 3")
print(arr*3)

after multiplication by 3
[ 30  60  90 120 150]


In [4]:
print("after division by 2")
print(arr/2)

after division by 2
[ 5. 10. 15. 20. 25.]


In [5]:
arr1 = np.array([1, 2, 3, 6, 4, 5]) 
print("reversed array")
reversed_arr = arr1[::-1]
print(reversed_arr)

reversed array
[5 4 6 3 2 1]


In [6]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

In [7]:
values,count = np.unique(x,return_counts = True)
max_count = np.max(count)
most_frequent = values[count == max_count]
print("Array x:", x)
print("Most frequent value:", most_frequent)
print("Frequency:", max_count)
for value in most_frequent:
    print("Indices of", value, ":", np.where(x == value)[0])

Array x: [1 2 3 4 5 1 2 1 1 1]
Most frequent value: [1]
Frequency: 5
Indices of 1 : [0 5 7 8 9]


In [8]:
y= np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
values,counts = np.unique(y,return_counts = True)
max_count = np.max(count)
most_freq = values[counts == max_count]
print("Array x:", y)
print("Most frequent value:", most_frequent)
print("Frequency:", max_count)
for value in most_frequent:
    print("Indices of", value, ":", np.where(y == value)[0])


Array x: [1 1 1 2 3 4 2 4 3 3]
Most frequent value: [1]
Frequency: 5
Indices of 1 : [0 1 2]


In [9]:
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("1st row, 2nd column" , arr[0,1])
print("3st row, 1nd column" , arr[2,0])

1st row, 2nd column 20
3st row, 1nd column 70


In [10]:
Akshat = np.linspace(10, 100, 25)
print("Array:")
print(Akshat)

print("\nDimensions:", Akshat.ndim)

print("Shape:", Akshat.shape)

print("Total elements:", Akshat.size)

print("Data type:", Akshat.dtype)

print("Total bytes:", Akshat.nbytes)

transpose_Akshat = Akshat.reshape(25, 1)

print("\nTranspose using reshape():")
print(transpose_Akshat)

transpose_T = Akshat.T

print("\nUsing T attribute:")
print(transpose_T)

print("\nShape using reshape:", transpose_Akshat.shape)
print("Shape using T:", transpose_T.shape)

Array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200

Transpose using reshape():
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Using T attribute:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Shape using reshape: (25, 1)
Shape using T: (25,)


In [11]:
ucs420_Akshat = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Original Array:")
print(ucs420_Akshat)

print("\nMean:", np.mean(ucs420_Akshat))

print("Median:", np.median(ucs420_Akshat))

print("Maximum:", np.max(ucs420_Akshat))

print("Minimum:", np.min(ucs420_Akshat))

print("Unique elements:", np.unique(ucs420_Akshat))

reshaped_ucs420_Akshat = ucs420_Akshat.reshape(4, 3)

print("\nReshaped Array (4 x 3):")
print(reshaped_ucs420_Akshat)

resized_ucs420_Akshat = np.resize(ucs420_Akshat, (2, 3))

print("\nResized Array (2 x 3):")
print(resized_ucs420_Akshat)

Original Array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped Array (4 x 3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized Array (2 x 3):
[[10 20 30]
 [40 50 60]]
