## Q1 :

In [1]:
import numpy as np
temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])
actual_temp = temperature+2
print(f"Corrected temperature : {actual_temp}")
fahrenheit = (9/5) * actual_temp + 32
print(f"Temperature in fahrenheit : {fahrenheit}")
temp_greater_32 = np.sum(actual_temp>32)
print(f"Temperature greater than 32 : {temp_greater_32}")

Corrected temperature : [27 30 33 37 40 29 35 42]
Temperature in fahrenheit : [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
Temperature greater than 32 : 5


### **Explain how vectorization and Boolean indexing can make data processing more efficient than explicitly iterating through every value.**


 **Vectorization performs operations on the entire NumPy array without explicitly using a for loop .**
 **Boolean indexing efficiently filters elements based on a condition .**

In [2]:
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

total_steps = steps.sum()
print(f"Total steps : {total_steps}")
mean_steps = steps.mean()
print(f"Mean of the steps : {mean_steps}")
maximum = steps.max()
minimum = steps.min()
print(f"Maximum steps is {maximum} and minimum is {minimum}")

daily_total = steps.sum(axis=0)
print(f"Total steps for each day : {daily_total}")

user_total = steps.sum(axis=1)
print(f"Total steps for each user : {user_total}")
max_index = steps.argmax()
position = np.unravel_index(max_index, steps.shape)
print("User/Day position:")
print(position)

print("Maximum steps:", steps[position])

Total steps : 84200
Mean of the steps : 7016.666666666667
Maximum steps is 9500 and minimum is 4500
Total steps for each day : [26500 27300 30400]
Total steps for each user : [18300 24500 14400 27000]
User/Day position:
(np.int64(3), np.int64(2))
Maximum steps: 9500


In [3]:
original = np.array([1, 2, 3, 4, 5, 6])

print("a. Original array:")
print(original)
subset = original[1:5]
print("\nb. Subset:")
print(subset)
subset[0] = 999
copied_array = original[1:5].copy()
copied_array[0] = 500
print("\nd. After modifying copied array:")
print("Original:", original)
print("Copied array:", copied_array)

matrix = np.arange(1, 13).reshape(3, 4)
print(" 3 x 4 Matrix:")
print(matrix)

first_row = matrix[0]
last_row = matrix[-1]
second_column = matrix[:, 1]
selected_elements = matrix[0:2, 1:3]

print("First row:")
print(first_row)

print("Last row:")
print(last_row)

print("Second column:")
print(second_column)

print("Rows 1-2 and Columns 2-3:")
print(selected_elements)

flatten_array = matrix.flatten()
ravel_array = matrix.ravel()

print(" Flatten:")
print(flatten_array)

print("Ravel:")
print(ravel_array)

ravel_array[0] = 100

print("\nh. After modifying ravel array:")
print("Ravel array:")
print(ravel_array)

print("Original matrix:")
print(matrix)

flatten_array[1] = 500

print("\ni. After modifying flatten array:")
print("Flatten array:")
print(flatten_array)

print("Original matrix:")
print(matrix)

print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)
print("Size:", matrix.size)
print("Data type:", matrix.dtype)

a. Original array:
[1 2 3 4 5 6]

b. Subset:
[2 3 4 5]

d. After modifying copied array:
Original: [  1 999   3   4   5   6]
Copied array: [500   3   4   5]
 3 x 4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row:
[1 2 3 4]
Last row:
[ 9 10 11 12]
Second column:
[ 2  6 10]
Rows 1-2 and Columns 2-3:
[[2 3]
 [6 7]]
 Flatten:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

h. After modifying ravel array:
Ravel array:
[100   2   3   4   5   6   7   8   9  10  11  12]
Original matrix:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]

i. After modifying flatten array:
Flatten array:
[  1 500   3   4   5   6   7   8   9  10  11  12]
Original matrix:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Shape: (3, 4)
Dimensions: 2
Size: 12
Data type: int64


In [4]:
y = np.array([40, 65, 30, 85])
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])
print("a. Shape of X:")
print(X.shape)

print("Dimensions of X:")
print(X.ndim)
XT = X.T

print(" Transpose X.T:")
print(XT)
XtX = X.T @ X

print("X.T @ X:")
print(XtX)

inverse = np.linalg.inv(XtX)

print("Inverse of X.T @ X:")
print(inverse)
beta = np.linalg.inv(X.T @ X) @ X.T @ y

print("\ne. OLS Coefficients:")
print(beta)

new_user = np.array([5, 40, 7])

predicted_score = new_user @ beta

print("\ng. New user:")
print(new_user)

print("Predicted assistance score:")
print(predicted_score)

a. Shape of X:
(4, 3)
Dimensions of X:
2
 Transpose X.T:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]
Inverse of X.T @ X:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]

e. OLS Coefficients:
[-0.15921454  0.14083853 10.06302242]

g. New user:
[ 5 40  7]
Predicted assistance score:
75.27862544779117
